trigger:
- master

pool:
  vmImage: 'ubuntu-latest'


steps:

- task: SonarQubePrepare@4
  inputs:
    SonarQube: 'Prueba'
    scannerMode: 'MSBuild'
    projectKey: 'Y5173wAv18wKsigzJ3AU'
    projectName: 'Prueba'

- task: SonarQubeAnalyze@4

- task: SonarQubePublish@4
  inputs:
    pollingTimeoutSec: '300'